### ISSUE TITLE
signalQuality value problems experineced by adm & others

### ISSUE THREAD

**Issue by EMJB** [OpenViX/enigma2#353] opened 2018-12-15 15:33 UTC
Thanks to a lot of help from birdman, I have been investigating the difficulties found by adm when using the ABM Frequency Finder, and have identified two separate problems as follows:

(1) When using the new DVB API for terrestrial signals, "signalQuality" is calculated by frontend.cpp in calculateSignalPercentage by comparing the "signalQualitydB" with 19 dB, such that 100% is reported for higher levels. However the "signalQualitydB" needs to be about 20 dB to achieve lock, so if lock is achieved signalQuality will almost certainly be 100% for all tuners correctly reporting signalQualitydB. The numbers for cable and satellite will be slightly different, but show similar effects. My suggested changes are included in the attached file.

(2) The Si2169 tuner driver in Xtrend's dvb.ko file reports the "FE_SCALE_DECIBEL" figure as "FE_SCALE_RELATIVE", leading to the use of the legacy API where frontend.cpp lacks any special code to correctly calculate either "signalQuality" or "signalQualitydB" for this tuner. I have included in my frontend.cpp changes to detect & correct this error when it occurs, but should not be activated should the driver ever be fixed.

A major factor in (1) was the apparent assumption by the author that the threshold for achieving lock is an Carrier-to-Noise Ratio of 0 dB rather  than ~20 dB. Similar assumption for SNR seem to be made in the legacy API calculations, so I would not be surprised if these also showed signalQuality values of 100% for quite modest signals.

I have taken the opportunity to provide more information on signal content and scaling is the code comments, as these do not seem to be documented elsewhere.

I have also looked at adding support for both BER and signal strength from the new API, but neither are supported by my tuner drivers, so I could not proceed.

EMJB

[fecppchanges.txt](https://github.com/OpenViX/enigma2/files/2682716/fecppchanges.txt)

**Comment by RobvanderDoes** [comment] 2018-12-16 04:16
Very interesting observations. I really hope that will result in a PR.

**Comment by EMJB** [comment] 2018-12-16 10:12
Unfortunately my attempts to raise a pull request under birdman's tutelage failed miserably - probably because I am often only able to spend short periods on this at any one time due to commitments as a carer, and it was a case of "more haste, less speed". I had hoped the difference file I attached would enable my suggested changes to be reviewed & incorporated.

**Comment by RobvanderDoes** [comment] 2018-12-16 10:37
Maybe you can send your changes to Birdman; he's used to raise pull requests.

**Comment by AbuBaniaz** [comment] 2018-12-16 11:30
Raising an Issue here is the same as reporting it on the forum.

With regards to creating a pull request, process is as follows. I'll do a pictorial guide on forum for benefit of others too.

Create a new branch, make sure it is from `Dev` not `Master`, maybe call it `si2169_signal`
Add your changes
Compare and pull request
Base fork/project will be Openvix, Branch is Dev. Head fork is your fork/project, Branch will be `si2169_signal` if that is the name you used

Do not add any more changes to your  si2169_signal branch unless they are related to the issue being dealt with. Delete it if/after the changes are merged.

If you don't have much success, I'll use the diff file to build a test image for adm and ccs

**Comment by AbuBaniaz** [comment] 2018-12-16 11:59
>If you don't have much success, I'll use the diff file to build a test image for adm and ccs

Looks like it is no point doing so as you have already run a build for the ET10000 with the changes

**Comment by EMJB** [comment] 2018-12-16 13:46
I have tested it on an ET10000 build with Si2168/9 , and birdman has done so on an ET8000 build with Si2168/9 & MN88473 tuners.

@AbuBaniaz - please note that as for as I can see the main issue relates to ALL cable, satellite, & terrestrial tuners using the new API, and it is only the second that applies to the Si2169. The name you suggest for the fork could imply you think this is mainly an Si2169 issue

A pictorial guide would help. One step that has eluded me is how to delete the fork I created when I first tried - when I try to create a new one it takes me to the old one. Also you refer to creating a new "branch" - is this the same as creating a "fork"?

EMJB

**Comment by AbuBaniaz** [comment] 2018-12-16 14:05
Well, use any name for your branch. It will get deleted anyway. Not going to do a romeo and juliet quote for you.

Fork = Copy a project to your own repository
Create branch = Create a new branch within your fork

I suggest you remove the was entries in the commit. If there is a problem, the history shows what the previous ones were

I have already applied the changes to my fork, link to it above. If you cannot do the pull request, I will submit for you at 23:00.

I am closing this issue now. AGAIN.

**Comment by RobvanderDoes** [comment] 2018-12-16 14:15
Please leave issues open until they are fixed.

**Comment by RobvanderDoes** [comment] 2018-12-16 14:19
Please leave issues open until they are fixed.

**Comment by AbuBaniaz** [comment] 2018-12-16 14:19
The issue is EMJB not able to submit a pull request.

**Comment by RobvanderDoes** [comment] 2018-12-16 14:20
Closing an issue as soon as it has been fixed is standard and decent practice; we always do that. 
This allows all participants to comment in this issue tracker, and is not related to who fixes it/submits a PR.

**Comment by ccs-ccs** [comment] 2018-12-16 21:15
I tried commenting on an old commit a while ago, probably not the correct procedure, but relates to this problem…..

https://github.com/OpenViX/enigma2/commit/60ae71f7f2102ea99b0e0ad63dd38c1c24d25483#diff-e3339c476cfa702e84570deec3be6efa

**Comment by EMJB** [comment] 2018-12-17 09:18
@ccs-ccs 
I think the code to which you refer is associated with the old (legacy) API, which I expect to cause problems but have been loathe to attempt to "fix" in case I do more harm than good. I think there is a specific problem in the case of the Xtrend Si2169 tuners where the returned value for SNR using the legacy API is a factor of 10 too high (currently the bug in the new API is causing reversion to the old API - hence birdman & I see SNR values of ~350 dB. As there is a theoretical lower limit for noise at ~-100 dB below 1 milliwatt, this corresponds to power levels of many gigawatts!).

**Comment by ccs-ccs** [comment] 2018-12-17 10:37
@EMJB Thanks for the explanation.

**Comment by EMJB** [comment] 2018-12-30 13:54
I have tried again to generate a pull request using Abu's procedures

EMJB

**Comment by RobvanderDoes** [comment] 2019-01-29 10:37
Is this still an issue, or can we close it?

**Comment by RobvanderDoes** [comment] 2019-03-06 09:13
No response in 5 weeks, so apparently no issue anymore.

**Closed by RobvanderDoes** 2019-03-06 09:13 UTC

**Comment by EMJB** [comment] 2019-03-06 09:46
I thought I replied to your email saying the original problem was resolved.

EMJB

**Comment by Huevos** [comment] 2019-03-06 13:12
100% and 16dB reported on the Edision Mio 4K. Is it really supposed to be like that?

**Comment by EMJB** [comment] 2019-03-06 13:49
@Huevos:
There are some separate problems arising from results of running a version of frontend.cpp with enhanced logging posted by Abu Baniaz & ccs. These appear to be associated with the use of the legacy API (sometimes unnecessarily, I think). The changes I put forward at the end of this year ONLY apply to the use of the new API, and it would appear that the legacy API requires specific code for each tuner model. Generation of that code requires results from a known SNR (which may be difficult), preferably with enhanced frontend.cpp logging.

With regards to the specific numbers, parts of frontend.cpp seem to have been written on the assumption that an SNR of 0 dB corresponds to marginal lock. 100% relative SNR and 16 dB absolute SNR are consistent with my memory of the legacy code foe DVB-S. 65535 does correspond to 100% relative SNR, and to 65.535 dB absolute SNR. If you could run the version of frontend.cpp with extended logging for your tuners it would confirm the problem and possibly point to a solution.

I have been trying to put together an overview of the problems and possible improvements in this area, and will try to get this finished in the next couple of weeks. It was my intention to raise a separate issue - is that the correct thing to do? 

EMJB

**Comment by Huevos** [comment] 2019-03-06 16:28
If 65535 corresponds with 100% why is 100% shown at 16dB? Mio is a modern box so should not be using legacy stats

**Comment by EMJB** [comment] 2019-03-06 17:51
@ Huevos:
"If 65535 corresponds with 100% why is 100% shown at 16dB?" A: If you look at "void eDVBFrontend::calculateSignalQuality(int snr, int &signalquality, int &signalqualitydb)" (which applies to the legacy API only) in frontend.cpp you will see that the maximum value of SNR used in the % calculation varies between tuners, but is sometimes below 16 dB.  The logic for the new API used to be similar, but the minimum SNR for lock was ~ 20 dB, and hence the % figure was always 0 or 100.

"Mio is a modern box so should not be using legacy stats." A: Agreed, which is why I would like to see the results of the extended logging so we can see what is going on. Abu Baniaz's  & ccs's logs indicate that some tuners only provide relative SNR via the new API, and currently this leads to the use of the old API for both absolute and relative SNR calculations. There would seem to be arguments for converting relative SNRs to absolute SNRs in these circumstances, but it is not without drawbacks which I am trying to establish & document.
 
EMJB
