### ISSUE TITLE
recording, playback and timeshift  settings page are broken

### ISSUE THREAD

**Issue by kiddac** [OpenViX/enigma2#896] opened 2023-09-24 17:59 UTC
you cannot scroll down the settings in recording, playback and timeshift settings. 
Its stuck on first option. See screen below.

**Comment by TwolDE2** [comment] 2023-09-24 19:43
Do you fast forward/rewind? 
IPTV or satellite? Or both?
need more explanation

**Comment by kiddac** [comment] 2023-09-24 19:45
sorry. I was in a rush. 
On my vu zero 4k
if you go in setup > recordings, playback & timeshift.
When in the inner menus, you cannot scroll up and down.

Default skin
Vix 6.4.007

**Comment by kiddac** [comment] 2023-09-24 19:47
![image](https://github.com/OpenViX/enigma2/assets/6818561/05dcd31a-5038-414b-99c6-f0596d622ee7)

**Comment by TwolDE2** [comment] 2023-09-24 20:00
Is this on any menu entry or just on 1st menu entry (default movie location)… if movie location and only one current location, , pressing OK will let you select a new location

**Comment by kiddac** [comment] 2023-09-24 20:08
you cant move from the first entry.
Changing the location doesnt effect anything

This also happens on timeshift menu. That also has a location as the first item.

nothing remarkable in debug logs

```
< 12515.5241> [RecordingSettings] valid partitions ['/']
< 12515.5257> [Skin] Processing screen 'Setup' from list 'RecordingSettings, Setuprecording, setup_recording, Setup', position=(0, 0), size=(1920 x 1080) for module 'RecordingSettings'.
< 12515.5380> [Skin] Parsing embedded skin '<embedded-in-SetupSummary>'.
< 12515.5386> [Skin] Processing screen '<embedded-in-SetupSummary>' from list 'RecordingSettings_summary, Setuprecording_summary, setup_recording_summary, Setup_summary, SetupSummary, SimpleSummary', position=(0, 0), size=(132 x 64) for module 'SetupSummary'.
< 12515.5396> [eWindowStyleManager] getStyle(style_id=1): NOT FOUND
< 12515.5441> [InfoBarGenerics] Key: 352 (Break) KeyID='KEY_OK' Binding='('OK',)'.
< 12515.5458> "::ffff:192.168.1.100" - - [24/Sep/2023:19:46:40 +0000] "GET /api/remotecontrol?command=352&_=1695584651120 HTTP/1.1" 200 84 "http://192.168.1.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
< 12516.5773> "::ffff:192.168.1.100" - - [24/Sep/2023:19:46:40 +0000] "GET /api/pipinfo?_=1695584651121 HTTP/1.1" 200 33 "http://192.168.1.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
< 12516.5818> [eConsoleAppContainer] Starting /usr/bin/grab
< 12516.7753> "::ffff:192.168.1.100" - - [24/Sep/2023:19:46:42 +0000] "GET /grab?format=jpg&mode=all&t=1695584802831 HTTP/1.1" 200 480698 "http://192.168.1.12/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
< 12517.8949> [InfoBarGenerics] Key: 108 (Make) KeyID='KEY_DOWN' Binding='('DOWN',)'.
< 12517.8956> [ActionMap] Keymap 'NavigationActions' -> Action = 'down'.
< 12517.8973> [InfoBarGenerics] Key: 108 (Break) KeyID='KEY_DOWN' Binding='('DOWN',)'.
```

**Comment by Huevos** [comment] 2023-09-24 21:37
It won't move unless to location is valid. 

It must be a file system capable of hardlinks, i.e. 'ext4', 'ext3', 'ext2', 'nfs', 'cifs', 'ntfs'.

According to your log /media/hdd is not. Are you using a FAT or similar drive?

**Comment by kiddac** [comment] 2023-09-24 21:57
hmmm, interesting. Its a fresh install. So its probably got a blank usb in the slot that hasn't been initialised. But if thats the case. Its still an error that needs amending. 

But... here is something strange. I just been messing with recording.py I deleted absolutely all functions and every line in init except for 

Setup.__init__(self, session=session, setup="recording")

and the entire screen loads and seems to work and scroll. Including the 3 location spots. 

![image](https://github.com/OpenViX/enigma2/assets/6818561/485eae07-1dbc-4e57-84fa-ea06da1231fc)

**Comment by Huevos** [comment] 2023-09-24 22:08
It is not a bug. It was coded not to move if the drive is not valid. But in my opinion needs a message to explain to the user what is happening.

**Comment by kiddac** [comment] 2023-09-24 22:11
I can confirm intialising the usb unfreezes that menu. 
I have been around these boxes a long time and should have known better. Probably like most of us old timers, we normally just stick in an initialised usb stick. So never see this issue. This time I formated my usb. 

But I was just about to write the same as you. It does need a message popup. 
If an experienced user overlooked this issue. A new person wouldn't have a clue what was wrong.

**Comment by kiddac** [comment] 2023-09-24 22:18
And freezing a setting, because its not valid isn't really great user experience or a good idea.

**Comment by Huevos** [comment] 2023-09-24 22:23
So just one other thing. This screen has a footnote widget and that tells you why it won't move. In ViX default skin it uses `<screen name="Setup">` which has that widget. So is that missing from the skin you are using?

```
	def pathStatus(self, path):
		if path.startswith("<"):
			self.errorItem = -1
			footnote = ""
			green = self.greenText
		elif not isdir(path):
			self.errorItem = self["config"].getCurrentIndex()
			footnote = _("Directory '%s' does not exist!") % path
			green = ""
		elif not self.isValidPartition(path):
			self.errorItem = self["config"].getCurrentIndex()
			footnote = _("Directory '%s' not valid. Partition must be ext or nfs") % path
			green = ""
		elif not fileExists(path, "w"):
			self.errorItem = self["config"].getCurrentIndex()
			footnote = _("Directory '%s' not writable!") % path
			green = ""
		else:
			self.errorItem = -1
			footnote = ""
			green = self.greenText
		self.setFootnote(footnote)
		self["key_green"].text = green
```

**Comment by kiddac** [comment] 2023-09-24 22:35
it just say "directory '/media/hdd/movie/" does not exist. Whether empty. Or not initialised. 
It does not say usb or hdd required to record. It does not say usb needs initialising. 

I will leave it with you. You can close this issue if you want and change it if you think it needs it.

**Comment by kiddac** [comment] 2023-09-24 22:36
![image](https://github.com/OpenViX/enigma2/assets/6818561/9b51d1fe-bed4-4471-a7bc-fc67af4b8f34)

**Comment by AbuBaniaz** [comment] 2023-09-25 14:44
People have been recording to non-ext file systems for a long time.  Other images still allow recording to non-ext file systems. The code was changed on Vix to avoid the timeshift errors because of link issue. There are two sections where permitted location is mentioned, one deals with timeshift, other recording. It would have been better if the changes for timeshift were made in the timeshift section.

You can actually have one location for recording and another location for timeshift.

**Comment by Huevos** [comment] 2023-09-28 22:56
@AbuBaniaz I not really sure what you are saying. There is not a hardlink restriction for recordings, only timeshift. FAT file systems are not capable of hardlinks. The problem in this thread was that the location didn't exist.

If you think there is a problem with recordings please post instructions how to reproduce it.

**Comment by Huevos** [comment] 2023-10-01 01:01
https://github.com/OpenViX/enigma2/commit/4fb6abb5477ece4561ed586144bb8376e51e9534

So in future if you try scroll down without setting up a valid location it will show a MessageBox with details.

**Comment by RobvanderDoes** [comment] 2023-11-14 21:17
Can we close this?

**Comment by Huevos** [comment] 2023-11-15 00:56
Yes

**Closed as completed by Huevos** 2023-11-15 00:56 UTC
