### ISSUE TITLE
Big5 is not displaying properly, often it crashes.

### ISSUE THREAD

**Issue by bohdan01** [OpenViX/enigma2#198] opened 2017-11-04 01:07 UTC
Hello, is there anyone that could help me with correctly decode big5.
I am using vu+ 4k in Taiwan DVB-T and seems that the EPG is coming in Big5.
That is part of error log
---------------------------------------------
10646-1 enc.
unsup. Big5 subset of ISO/IEC 10646-1 enc.
unsup. Big5 subset of ISO/IEC 10646-1 enc.
unsup. Big5 subset of ISO/IEC 10646-1 enc.
unsup. Big5 subset of ISO/IEC 10646-1 enc.
not pauseable.
-------------------------------------------
actually to make sure I would like to find out how to grab row epg to see what actually is provided.
I have tried to use ecoding.conf to set some parameters. although it has several different section in that file that I was not able to find description of use.
1st section has country code then code page, 
then is commented code page that describes the Fallback encoding page, but its commented so can it be specified or is hard coded?
2nd  has TSID ONID numbers in Hex 
3rd again follows with same thing just that numbers seems to be in decimal and includes code page.
how is it organized?
Is the problem of my misunderstanding of encoding.conf or there is problem in the code?

Could someone point me in the right files and direction.
thank you

I have tried the following config in encoding.conf
twn Big5  // one try
twn CP950 // other try

TSID ONID
#0x0018 0x209E BIG5

#Fallback encoding table for single transponders
#ISO6937 also enables two byte char encoding
#TSID ONID ISO8859-X
#24	8350 Big5

Its based on DVB-T in Taiwan 
1_0_1_12E_1C_209E_EEEE0000_0_0_0		民視新聞台 - FTP 2-302
1_0_1_130_1C_209E_EEEE0000_0_0_0		民視台灣台  FTP-4-304
1_0_1_190_20_209E_EEEE0000_0_0_0		台灣電視台 HD - TTV-400
1_0_1_191_20_209E_EEEE0000_0_0_0		台視新聞台 HD - TTV-401
1_0_1_192_20_209E_EEEE0000_0_0_0		台視財經台 - TTV-402
1_0_1_193_20_209E_EEEE0000_0_0_0		台視綜合台 - TTV-403
1_0_1_12C_1C_209E_EEEE0000_0_0_0		民視- FTP-0-300
1_0_1_12D_1C_209E_EEEE0000_0_0_0		民視第一台 - FTP-1-301
1_0_1_12E_1C_209E_EEEE0000_0_0_0		民視新聞台 - FTP 2-302
1_0_1_130_1C_209E_EEEE0000_0_0_0		民視台灣台  FTP-4-304
1_0_1_C8_1E_209E_EEEE0000_0_0_0		公共電視 3 HD - PTS-200
1_0_1_CC_1E_209E_EEEE0000_0_0_0		客家電視 - HakkaTV HTV-1-204
1_0_1_CD_1E_209E_EEEE0000_0_0_0		TiTV-205
1_0_1_1F5_22_209E_EEEE0000_0_0_0		華視HD - CTS HD-501
1_0_1_1F6_22_209E_EEEE0000_0_0_0		華視教育文化 HD - CTS-502
1_0_1_1F7_22_209E_EEEE0000_0_0_0		華視新聞資訊台 HD - CTS-503
1_0_1_1F8_22_209E_EEEE0000_0_0_0		國會頻道1 - CTS-504
1_0_1_1F9_22_209E_EEEE0000_0_0_0		國會頻道2 - CTS-505

**Comment by opfans** [comment] 2018-12-17 09:35
taiwan dvbt and 88KU st2 programme,EPG is encodee by UTF16BE.you can use openatv image,taiwan dvbt programme epg correctly decode .

**Comment by opfans** [comment] 2018-12-17 09:48
if you have problem ,add my QQ 392814736 or wechat 13290787030

**Comment by opfans** [comment] 2018-12-25 12:00
NOW,you can use openvix image ,add tsid onid E:UTF16BE on encoding.conf ,the issue fixed.

**Comment by AbuBaniaz** [comment] 2018-12-25 14:17
If the problem is fixed, please close the issue.

If we need to add a commit another team has made, please post a link to the commit.

**Comment by opfans** [comment] 2019-01-18 05:18
> If the problem is fixed, please close the issue.
> 
> If we need to add a commit another team has made, please post a link to the commit.
This commit  https://github.com/OpenViX/enigma2/commit/78ecd375f0cffffe1d62b182c03fc76cb412c23a  have fixed the issue,i cant close the issue because i have no authority.Only openvix team can close it.

**Comment by opfans** [comment] 2019-01-18 05:19
> If the problem is fixed, please close the issue.
> 
> If we need to add a commit another team has made, please post a link to the commit.

This commit 78ecd37 have fixed the issue,i cant close the issue because i have no authority.Only openvix team can close it.

**Closed** 2019-01-18 06:05 UTC
