### ISSUE TITLE
Use LRU caching for all pixmaps

### ISSUE THREAD

**Issue by kiddac** [OpenViX/enigma2#366] opened 2019-01-17 19:14 UTC
https://github.com/OpenViX/enigma2/commit/df56a9ccc9c3a5fe4cf417c1fc80f52de76ec8b3

You have wrongly made the assumption that all pixmaps are static and never change. 
This is not the case. This caching of pixmaps has now broken all my skins that bring in cover art for channels as they use the same png name.
To fix this I am now providing all my users a copy of the OpenATV LoadPixmap.py. 

Can you please undo this LRU caching for all pixmaps, there was nothing wrong with the original LoadPixmap.py  Thanks.

**Comment by RobvanderDoes** [comment] 2019-01-17 19:23
Who are 'my users'?

**Comment by kiddac** [comment] 2019-01-17 19:30
The OpenVix users of my skins, that are now finding things broken because of this change.

**Comment by ViX-Sicilian** [comment] 2019-01-17 19:35
No one revert anything at the moment, not until current release build completes.

**Comment by RobvanderDoes** [comment] 2019-01-17 19:40
What are 'your skins'?

**Comment by kiddac** [comment] 2019-01-17 19:40
The problem is that myself and people like Chab's bring in image scrapes in their skins, that bring cover art into certain screens. These multiple images use the same png name. i.e tile1.png, tile2.png. etc

These are now being cached unless the gui is restarted to refresh them, so they are not changing at a set timeinterval as expected. 

The commit mentioned cache unless specifically disabled. What is the alternative of how to disable caching in my python component???

**Comment by RobvanderDoes** [comment] 2019-01-17 19:42
And who is 'Chab'?

**Comment by kiddac** [comment] 2019-01-17 19:48
Next you will be asking who is Rossi, Who is Digiteng?

**Comment by Huevos** [comment] 2019-01-17 19:54
@kiddac, if the "cache" is displaying the wrong images the commit will be reverted.

**Comment by ViX-Sicilian** [comment] 2019-01-17 19:57
We will have to wait after this build completes please. I’ll do another release build in day or two after completes.

**Comment by kiddac** [comment] 2019-01-17 19:58
Thank you. It's not displaying the wrong images as such. The component is doing its job - Caching the images. But some of us obviously lesser known skinners :)) do funky things with changing the images for visual eye candy . So we do not need the caching of all pixmaps, or at the very least need a solution to get around the caching in our custom components.

**Comment by SimonCapewell** [comment] 2019-01-17 21:07
@kiddac Are these image names outside of the names referred to in the OpenVix code or are they used in the additional custom components you distribute with your skins? I was looking at adding static caching in EPGList.py for all the little graphics used in the grid to try to get it loading more snappily, but would have to shelve that idea if this breaks stuff.

**Comment by kiddac** [comment] 2019-01-17 21:16
They are just pngs brought in iwith ePixmap for example. In this example on the menu screen.

`	<ePixmap pixmap="q-toppicks/toppicks1.jpg" position="542,386" size="246,327" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks2.jpg" position="806,386" size="246,327" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks3.jpg" position="1070,386" size="246,327" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks4.jpg" position="1334,386" size="246,327" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks5.jpg" position="1598,386" size="246,327" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks6.jpg" position="542,780" size="240,320" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks7.jpg" position="806,780" size="240,320" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks8.jpg" position="1070,780" size="240,320" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks9.jpg" position="1334,780" size="240,320" backgroundColor="mid" transparent="0" zPosition="2" />
		<ePixmap pixmap="q-toppicks/toppicks10.jpg" position="1598,780" size="240,320" backgroundColor="mid" transparent="0" zPosition="2" />`

but these images get changed via a cron. But as they are now cached all the time. They no longer change. 

![image](https://user-images.githubusercontent.com/6818561/51349319-e45c8600-1a9c-11e9-83d0-ca8377787258.png)

**Comment by Huevos** [comment] 2019-01-17 21:35
@SimonCapewell I tried caching with picons a while ago and didn't see any performance gain. Rob suggests there is a performance benefit for older receivers such as the Ultimo with this code. But that is academic if it leads to non-static images not displaying correctly.

Personally I would rather avoid caching altogether and any pull requests that contain it.

**Comment by IanSav** [comment] 2019-01-17 21:35
If you look at the LoadPixmap source you will find that you can turn the caching off on demand:

    def LoadPixmap(path, desktop=None, cached=None):
        if cached is None or cached:
          ret = _cached_load(path, desktop)
          return ret
      else:
        return _load(path, desktop)`

Adding a "cached=False" to your LoadPixmap commands should suppress the caching.

**Comment by Huevos** [comment] 2019-01-17 21:37
Ian, that is just another example of the tail (skin) wagging the dog.

**Comment by kiddac** [comment] 2019-01-17 21:39
Yes but the image is loaded via skin code epixmap (which uses loadpixmap.py. The image is only changed in its original location, but has the same name. So as far as I am aware you cannot put cache="false" on the epixmap in the skin. Correct.

**Comment by IanSav** [comment] 2019-01-17 23:37
Huevos, I look at it as using the options as always provided but only recently activated.  The caching intention was apparently coded about 11 years ago though it wasn't activated until recently.  The "cache" argument has been around for a VERY long time and is included in OpenPLi, OpenViX, OpenATV and Beyonwiz.  (I only checked those four images.)

Remember that I am not behind this change.  I can say that it has improved UI performance in the Beyonwiz image, from where this code was cherry picked.

**Comment by Huevos** [comment] 2019-01-17 23:40
Ok, but it needs to be accessible from the skin then.

**Comment by Huevos** [comment] 2019-01-17 23:41
Then all parties would be happy.

**Comment by IanSav** [comment] 2019-01-17 23:45
Kiddac, I suspect that you are correct.  The name, not the content is cached so this may still be a problem for you.

There are simple ways that this could be addressed, like checking some inode parameters to see if the file content has changed (this would have a lesser performance but still better than not caching at all), but perhaps this is beyond the scope of this issue.

**Comment by IanSav** [comment] 2019-01-17 23:50
Huevos, if the caching algorithm is tweaked then the caching could be fully automatic and transparent.  No skin changes would be required.

**Comment by SimonCapewell** [comment] 2019-01-18 09:48
Just in case anyone is in any doubt about performance benefits of caching, I've measured a 100ms load time on my Xtrend 8500 for the ~50 pngs required by the graph EPGList code without caching. Total load time for the screen tends to be around 800ms IIRC, which is long enough to wonder if the machine saw your button press. With this caching, it drops to around 20ms.

**Comment by SimonCapewell** [comment] 2019-01-18 11:19
I'll have a look over the weekend. The algorithm will be to checking the image's updated time against the one stored in the cache and the file is newer, refresh the image in the cache.

**Comment by andyblac** [comment] 2019-01-18 11:22
not sure how the cache works, but it would be better to make a checksum of the file in cache and compare that to the local file if it does not match then update the cache, rather than just going off date/time.

**Comment by SimonCapewell** [comment] 2019-01-18 11:45
If it's a CPU bound issue, then turning the content into a png object will be the bottleneck and the checksum approach will be good. If it's IO bound then checksum won't be such a good idea. In my normal line of work, my money would be on IO being the bottleneck, but this is slightly different class of hardware! Best think is to profile all 3 approaches (updated time, checksum, no caching) and make a decision based on the result.

**Comment by andyblac** [comment] 2019-01-18 12:10
do some tests, but from my past experience and guess it is a CPU issue, as the graphics is (from what I remember, but this was before ARM) was all done in the CPU cycles, I don't think flash ie I/O is the issue.

**Comment by IanSav** [comment] 2019-01-18 13:41
Processing the image files in any way will defeat the cache and the purpose of caching the files in the first place.

If the tests can be based on only data available in the inode then this will come from RAM as the inodes are usually in system cache.  The cost to query an inode value should be SIGNIFICANTLY less than finding and accessing the actual file in the filesystem (for example the find, open, process and close time for accessing the actual file).  Times, inode number, etc could all be a basis for validating the image cache and either using the cache image or refreshing the cache.

In Kiddac's case his fancy displays should refresh much faster and consume less system resources while a image is stable and cached.  With the proposed cache validation the image caches should all reset and reload the images when the cron job swaps the images around.  They will then reload faster until the next cron loop.

**Comment by ViX-Sicilian** [comment] 2019-01-18 13:50
Guys, what do we do with this? Is this something that can be resolved in the near future or do we revert this this until resolved? I'm bumping DEV builds later today so would like to make a decision.

**Comment by RobvanderDoes** [comment] 2019-01-18 13:53
There is no hurry. The only person complaining about this, has a work-around.

**Comment by IanSav** [comment] 2019-01-18 13:55
I can't work on it in the near future.  Perhaps SimonCapewell will be able to complete his evaluation over the weekend as he proposed.

**Comment by kiddac** [comment] 2019-01-18 14:44
> 
> 
> There is no hurry. The only person complaining about this, has a work-around.

I only have a work around when people say how do I fix this in your skin and then I have to manually give them the old loadpixmap.py to load onto their box.

But I assume this is going to be a problem for any image that is used a placeholder and then that image changed in the background. 

I haven't tested this, but this might effect things like the IMDB plugin that brings in cover art, it will most certainly effect iptv plugins that download picon art in realtime. 

It will probably effect dreamplex plugin that downloads backdrops, cover art, music art. Etc. 

So I don't think its just a case of just affecting mine and a handful of other skins.

**Comment by IanSav** [comment] 2019-01-18 15:01
You could use the "cache=False" option in your LoadPixmap code to suppress the caching.

From memory IMDb is working fine with the cache code in place.  I don't think it uses LoadPixmap.

**Comment by kiddac** [comment] 2019-01-18 15:23
IanSav we are talking about images in skin screens <ePixmap pixmap="blahblah".... That use loadpixmap.py via the code in skin.py.

**Comment by IanSav** [comment] 2019-01-18 15:33
You mentioned the poster image in IMDb.

This is the skin widget

    <widget name="poster" position="4,90" size="96,140" alphatest="on" />

Here is the code that creates that widget:

    self["poster"] = Pixmap()
    self.picload = ePicLoad()
    self.picload.PictureData.get().append(self.paintPosterPixmapCB)

There is some screen scraper code and an image fetch from IMDb to get the poster image.

And here is the code that changes the image:

    def paintPosterPixmapCB(self, picInfo=None):
        ptr = self.picload.getData()
        if ptr != None:
            self["poster"].instance.setPixmap(ptr)
            self["poster"].show()

As you will note the LoadPixmap code is not used.

**Comment by RobvanderDoes** [comment] 2019-01-18 15:37
I never observed any issues in IMDB.

**Comment by kiddac** [comment] 2019-01-18 15:37
I am not on my box at the moment. Was just thinking of plugins that could be potentially affected. Not checked any of the code of anything at the moment

**Comment by kiddac** [comment] 2019-01-18 18:20
Just to add further confusion to this.
I have just installed openvix's version of loadpixmap.py and LRUCache.py to my openatv build. (I don't have a vix compatible box)
Despite copying over the python components my images still quite happily change. Yet several people are telling me they no longer change after they updated there openvix.  

![image](https://user-images.githubusercontent.com/6818561/51405122-5d1b1b00-1b4d-11e9-8e5f-fdff97a00727.png)

Checking the individual python modules, I do not have "from thread import RLock" on my OpenAtv. Is this needed for the cache of the files to happen. 

Because at the moment I am unable to do any further testing on this, and just relying on people telling me what is broken after this component update.

**Comment by RobvanderDoes** [comment] 2019-01-18 18:32
I think we should not be chasing 'hear say' (or ghost) issues.

**Comment by kiddac** [comment] 2019-01-18 19:01
OK, everyone is lying. Thanks for breaking something that wasn't broken in the first place.  Have a nice day.

**Comment by ViX-Sicilian** [comment] 2019-01-18 19:06
@ Rob, this is a genuine issue that i've seen reported.

If a resolution is not found I will be reverting this.

**Comment by IanSav** [comment] 2019-01-19 01:01
@Kiddac, without seeing your code it is difficult to theorise an explanation for the issue reports.  Given that all the problems started when the cache code was reactivated I would suggest that we give SimonCapewell a little time to complete his research and perhaps he can improve the cache and the whole issue can be addressed by the end of this weekend.

**Comment by SimonCapewell** [comment] 2019-01-19 01:33
@kiddac Most likely you're running your box with more graphics loaded than some of your users so you've got cache rotation refreshing the images. This would also explain why some people are having problems and others aren't. If I'm understanding the cache code correctly, there are 256 entries, which given the use of 50 entries by just the grid EPG, you can easily see more than 256 individual graphics getting used up in a graphics heavy skin.

**Comment by AbuBaniaz** [comment] 2019-01-19 02:17
Issue is not specific to EPG, even in the main menu it is manifest according to these posts.
https://linuxsat-support.com/thread/134771-skin-support-post-questions-for-all-my-skins-in-here/?postID=476099#post476099

He doesn't use ViX, might be an idea for those looking at the issue to load his skins.

**Comment by RobvanderDoes** [comment] 2019-01-19 03:12
> OK, everyone is lying. 

I have no idea about that. 
We have a policy of reproducing issues before looking into possible solutions. We don't know about these skins, we don't have them on our feeds and we can't possibly prevent or solve issues with all kinds of exotic plugins.
Please feel happy about the fact that you have found a simple a work-around, and that in spite of the above mentioned arguments already two of our team members have offered help to look into this.

**Comment by kiddac** [comment] 2019-01-19 16:35
I appreciate those people looking into my concerns regarding this update and understanding the potential issues, while others are dismissive of it. 
And just because openvix skins are very standard, with the only images being backgrounds, selectbars and icons, it doesn't mean the issue I have raised isn't a potential problem for other skins and plugins.
As for saying we don't know about these skins, people like IanSat, Huevos, AbuBaniaz are fully aware of mine and Chab's skins presense as they are some of the post popular skins used in the UK. So this isn't a problem only effecting a handful of people, it's potentially effecting a lot of users of OpenVix. 

And I will reiterate. Making people load an alternative loadpixmap.py onto their box or me including it in my IPKs is not a solution. It is an unnecessary workaround.

**Comment by Huevos** [comment] 2019-01-19 16:39
Yes, we are very accommodating even to people that have given us plenty of stick in the past.

**Comment by SimonCapewell** [comment] 2019-01-19 18:58
Something I've just noticed is that the c++ side has static caching already for `loadPNG` with no file updated or LRU refresh logic; you can see the code in *epng.cpp* `pixmapFromTable`.  `loadJPG` on the other hand doesn't. @kiddac did you ever try to use PNGs for these refreshing images whilst developing the feature, or were they jpgs from the start?

So my current understanding is that having the caching in the Python side isn't right. PNGs will currently be cached twice in memory. Once in the C++ layer, once in the Python layer which will be using more memory that necessary. However a question mark still hangs over why the graph EPGs 50 pngs are so much quicker to load when cached in static Python variables. My guess would be marshalling between the 2 layers, but it's just a guess.

**Comment by kiddac** [comment] 2019-01-19 22:35
My rotating cover images were originally pngs, but they could be reduced alot in size by using jpgs. So I now use jpgs for these images. 

I don't fully understand what you are say, but if I run a job Manager (script runner), to change these images manually. They are currently cached (with old code) until I fully exit out of menus. Once you go back in menus they reload. So there is some sort of caching going on already. Which is fine. 

I don't know how or why this pixmap caching has come about, but if its to overcome the hundreds of picons on channel select and epg, why don't you just cache the picons. (if they are not already)

I know cache works differently on linux as it always tries to fill the cache, but through my experience a full cache on these boxes actually slows them down, rahther than speeds things up. Most people even on newer boxes still use cacheflush plugin to constantly keep things buzzing along nicely.

**Comment by AbuBaniaz** [comment] 2019-01-19 22:51
The only recommendation for usage of cache flush plugin is for the original duo receivers with leaking memory fault. You won't find any experienced users on the Vix forum  recommending usage of cache flush plugin on recent receivers.

**Comment by kiddac** [comment] 2019-01-19 22:52
This maybe the case AbuBaniaz, but try using your box with 75% memory full and then running cacheflush plugin to reduce it to about 40% memory and notice the speed difference in response from your box.

**Comment by IanSav** [comment] 2019-01-20 01:18
@kiddac It is more than just the picons that benefit from caching.

I still think that verifying the cache contents is the better way to go.  The cache can be at the C++ or Python layers.  It shouldn't be in both.  ;)

**Comment by IanSav** [comment] 2019-01-20 01:38
@kiddac: Have you tried using the "cache=False" on your LoadPixmap commands and giving the test code to your OpenViX users reporting problems?  That should confirm if the new caching is the cause of the reported OpenViX issues.

**Comment by SimonCapewell** [comment] 2019-01-20 11:40
Yes, PC users have been sold memory maximizer snake oil for years, which do little more that clear the cache and then show how much memory is free. Having memory sat there doing nothing isn't making good use of it unless you know you're going to need it for transient spikes of demand. Where cache flushing works is where you're short of memory and the cache is too large for the total memory or is holding onto the wrong data, forcing swapping to disk when these spikes of demand come in.

It's worth pointing out that the cache for PNGs in *epng.cpp* isn't a proper cache, it's just a static store, from which images are never expired. This is probably why *loadJPG* doesn't have the same mechanism - it'd be a very bad idea to cache every photograph you view as you browse through the media plugin!

**Comment by IanSav** [comment] 2019-01-20 12:05
Are you thinking of improving/fixing the C++ caching and adding the JPG cache or moving the caches to Python (and fixing them there)?

**Comment by RobvanderDoes** [comment] 2019-01-29 10:24
Can this be closed as fixed by https://github.com/openvix/enigma2/commit/80abf40a6a019bcf9bff50f3921d3af29a1ae733 ?

**Comment by davesayers2014** [comment] 2019-02-16 11:39
Sorry is the issue fixed by using jpg rarther than png? As the images still don't change without restarting gui unless I change them to jpg

**Comment by IanSav** [comment] 2019-02-16 12:05
The solution chosen to address caching problems was to make .png images to be cached and .jpg files to not be cached.  You can still override .png caching by nominating "cached=False" in the LoadPixmap call..

**Comment by davesayers2014** [comment] 2019-02-16 12:10
Thanks so how do I modify the toppicks.xml?

<ePixmap pixmap="q-toppicks/toppicks2.jpg" position="806,386" size="246,327" backgroundColor="mid" transparent="0" zPosition="2" /> 

To

<ePixmap pixmap="cached=False"q-toppicks/toppicks2.jpg" position="806,386" size="246,327" backgroundColor="mid" transparent="0" zPosition="2" /> 

Will using "cached=False" cause issues with images that don't have this feature?

**Comment by IanSav** [comment] 2019-02-16 12:16
Direct access to the cache control is via Python code and not the skin.

**Comment by davesayers2014** [comment] 2019-02-16 12:18
Ok I'll use jpg rarther than png.

**Comment by SimonCapewell** [comment] 2019-02-16 14:37
Yes, whilst it would have been possible to add a cache flag to `ePixmap`, it wouldn't have any effect on pngs due to caching in the C++ side of E2. Using jpgs is the way to go at this stage.

**Comment by kiddac** [comment] 2019-02-19 19:16
Closed as fixed????? Quite simply dsayers, the issue is not fixed, and they seem unprepared to back track this unnecessary pixmap caching. Using jpgs isn't a solution because it wasn't broken in the first place.  More and more people are beginning to complain about it this, but what is the point in spending days trying to explain the problem to be totally ignored.

**Comment by ViX-Sicilian** [comment] 2019-02-19 20:30
Commits causing this issue should all now be reverted.

**Comment by IanSav** [comment] 2019-02-19 22:59
Rather than going backwards, why not add the skin cache control I suggested above?  With the cache controllable in both code and the skin we could then allow caching for all images while allowing coders and skinners to turn off the caching where appropriate or where caching has undesirable effects.

**Comment by RobvanderDoes** [comment] 2019-02-20 02:37
Going backwards is soooo much easier....

**Comment by IanSav** [comment] 2019-02-20 05:30
"Easier" rarely equates to "better".  ;)  Let's not throw the baby out with the bath water.

In this case it has been shown that caching can improve the performance of many Enigma2 skin / screen displays.  The users who will benefit from the caching should not be excluded from consideration against the issues that caching has triggered.

A suggestion has been made on how the issue can be resolved.  Why can't this suggestion be considered?

**Comment by ViX-Sicilian** [comment] 2019-02-20 06:29
I reverted these because no one has been able to provide a working fix. If a solution is found please submit a PR or post the files so that we can test.

**Comment by SimonCapewell** [comment] 2019-02-20 10:07
Does the revert provide the desired behaviour. As I mentioned earlier, there's caching in `epng.cpp loadPNG` which may continue to prevent pngs from refreshing: https://github.com/OpenViX/enigma2/commit/30300b8a686fde636cf21c1f9786c92b23a49d91

Removing the c++ layer caching may help, but there may also be places where the c++ layer is calling loadPNG directly that would be impacted. Careful consideration is needed before changing.

**Comment by IanSav** [comment] 2019-02-20 15:20
@Simon, do you have the interest and time to fix this mess?  That is, in my opinion:
1. Restore the reverted cache code
2. Remove the C++ PNG image cache code
3. Add Python caching for JPG images as well as PNG images
4. Add a `cache="0"` attribute to the ePixmap skin code to allow the cache to be disabled on demand for skin based images (in addition to the LoadPixmap cache control).

**Comment by SimonCapewell** [comment] 2019-02-20 17:36
I've probably got the time. What I haven't got is any idea how to do a typical dev cycle on the c++ side. How do I do the build? How do I get my modified source into the build? Where do I edit my branch? Do I need to push it up to my github repo every time I want to do a build? 

How to get up and running with a dev environment should really be in the readme or a wiki on the github repo - it'd be much better to have a coherent set of instructions, rather than hints being fragmented amongst various forum posts.

**Comment by Huevos** [comment] 2019-02-20 19:23
Simon if you want I can add a feature branch to my enigma repo and build it for you. Then once you are happy with it we can push to dev branch for wider testing.

**Comment by SimonCapewell** [comment] 2019-02-20 21:27
Thanks, that might be an option, but the ideal would still be to have an easily maintainable step by step guide though. 

So, after a bit of digging around, I've found a comment against the original commit of the c++ code in `epng.cpp` that mentions the caching there as being ref counted. The code is quite well commented re deadlocks and pitfalls, but doesn't mention this vital fact and to someone not well versed in this area, this isn't obvious. What this means is that PNGs tend to be cached on the c++ side, but only for the lifespan of the screen or component that refers to them. This means that the caching has no benefit for static screens like the main menu where you might have a pretty icon (e.g. Confluence skin). For something like the graph EPG, loads of graphics get loaded every time you open the screen, none of these will be loaded from cache, and as you scroll around, the graphics aren't loadedit, so for example if you make a change to the timer icon on the graph EPG cells whilst the graph EPG is open, it isn't reflected until the screen is destroyed and reopened.

A quick test without the Python caching shows this mixed bag. I can hack around with said menu icons and they're loaded on the fly next time I open the screen, however if I hack around with icons related to the volume control, they aren't picked up as this screen is loaded at startup, so retains its reference. Opening and closing the graph EPG picks up any changes too.

So, I'm intrigued by this c++ caching as it appears to have rather limited benefit with my current understanding of the code. The scenarios where it's likely to kick in are:
* Skins where the same png is referred to multiple times within a screen
* Skin frames when opening cascading dialogs (assuming the original dialog remains in memory)
* Code like this, where png2 would be loaded from cache:
```
png1 = loadPNG("big_picture.png")
png2 = loadPNG("big_picture.png")
```

Doing this would probably load from disk both calls
```
png1 = loadPNG("big_picture.png")
png1 = None
png2 = loadPNG("big_picture.png")
```

**Comment by AbuBaniaz** [comment] 2019-02-21 00:50
You can define your branch to build from in site.conf.  I don't build regularly, but I have a branch called `build_branch`. Enigam2 is built from there. I would strongly recommend you add the lot of baggage plugins we keep sifting through during a build for no reason into the plugin not wanted. 

```
SCONF_VERSION = "1"
BB_NUMBER_THREADS = "32"
PARALLEL_MAKE = "-j 16"
BUILD_OPTIMIZATION = "-march=native -O2 -pipe"
DL_DIR = "/home/openvix/sources"
INHERIT += "rm_work"
ENIGMA2_URI = "git://github.com/AbuBaniaz/enigma2_OpenViX;protocol=git;branch=build_branch"
DISTRO_FEED_URI = "192.168.0.70/feeds/${DISTRO_NAME}/${DISTRO_TYPE}/${DISTRO_VERSION}/${MACHINE}"
```

**Comment by SimonCapewell** [comment] 2019-02-21 19:25
Thanks. I'll have a go with that later.

Meantime, results from a proper test of the c++ caching show that it's as fast as the Python caching. Sub millisecond time to call `LoadPixmap` when the image is in the c++ cache regardless of image size.

**Comment by ViX-Sicilian** [comment] 2019-02-21 21:38
Simon, you should have access to the guest dev room on our forum, please confirm you can have access.

**Comment by SimonCapewell** [comment] 2019-02-21 21:39
Yes

**Comment by kiddac** [comment] 2019-02-24 16:01
and you can't add the cache control to the skin, because that would make the skin crash in any image that doesn't have this parameter.

**Comment by RobvanderDoes** [comment] 2019-02-24 16:59
The days of one skin fits all are long over, years ago.
That's why we have dedicated skins for ViX, that's why I have a skin for ViX, one for PLi and one for ATV.
Skinning and maintaining skins does take some effort, and you can't expect an image to be adapted for your skin; that would be the world upside down.

**Comment by SimonCapewell** [comment] 2019-02-24 19:07
@kiddac Does that happen in other images? If I add a load of rubbish attributes to the end of an ePixmap element Vix ignores them and outputs `[Skin] Attribute not implemented: thisdoesntexist value: whatisthisrubbish` to the log.

I'm considering using a file modified check anyway, pending performance tests.

**Comment by Huevos** [comment] 2019-02-24 22:19
I'd rather use an md5 signature if possible. Not sure how much overhead there would be for that.

**Comment by Huevos** [comment] 2019-02-25 10:43
kiddac alleges that the same issue affects a number of Enigma2 plugins. The allegations have never been investigated and don't seem to have any basis.

kiddac has not been forthcoming with his code (which is most probably where the underlying problem is).

On the issue of image load problems in the IMDb plugin, it's impossible for changes in LoadPixmap() to affect the loading of movie posters in the plugin, because the IMDb plugin doesn't use LoadPixmap() (or even loadJPG()) to load its poster images, it uses ePicLoad(), which is completely uncached. Almost all issues with information not loading in the IMDb plugin are due to IMDb's content management system changing its generated HTML and breaking the screen scraping regular expressions.

**Comment by Huevos** [comment] 2019-02-25 10:52
@SimonCapewell, if filemtime gives the desired effect without the IO request maybe we should probably go with that. We use filemtime in ABM for the caching of providers' files and it works well there. Several seconds are saved not reading those xml files. And when new files with identical filenames are imported the cache updates itself.

**Comment by prl001** [comment] 2019-02-25 11:57
> I'd rather use an md5 signature if possible. Not sure how much overhead there would be for that.

The architecture of loadPNG() makes it hard to directly access the file bytes to calculate any file checksum. Also, calculating a checksum requires the file to be read, so the caching only saves decode time, and not file I/O time.

**Comment by kiddac** [comment] 2019-02-25 22:09
> "The days of one skin fits all are long over, years ago.".

.. er no.. for the last 3 years I spent a lot of time making my skins work for as many OE-alliance builds as possible. Yes it is a lot more effort which is why most skinners don't. But it is still rewarding to do so, and then frustrating when 1 image decides to break things. 

> "you can't expect an image to be adapted for your skin;"
This wasn't broke in the first place until someone decided to change it. 

@SimonCapewell I stand corrected as I have just tested this and I thought this would throw up an error and therefore be a problem for anyone that had 'crash on skin error set'. It only throws up a warning, so its not a problem. 

@Huevos I initially said this may cause potential problems for plugins. It was made clear to me plugins we can work around in the plugin code. The main concern is skins that do clever eye candy by swapping images. As for not being forthcoming with my code. I explained what my code was doing. 
For example. I might have 10 images in a folder. 
tile1.png
tile2.png
tile3.png

Then via a cron, I run a particular py file which scrapes the new images and then swap these images out above with the new images. Using the PIL library to do some resizing and combing first. This is a jpg example but some I use pngs. 

im.save(skin_folder + image_folder + image_prefix + str(x) + ".jpg",quality=85) 

But as you have cached these images in my image folder, they will never change unless I restart GUI. 

And yes the underlying problem is it does effect all my skins. Hence why I brought up the issue in the first place. And if it was such a minor throw away issue why is this now one of the longest threads on your github. I have raised a very valid point and I am glad people are looking into the issue rather than just having being dismissive of it. 

No one has actually explained the real benefit of this change. Its 2019, nearly all boxes are duo core or quad core and memory sizes are being ever increased. Is saving a few nano seconds for the load time of a screen of any real noticeable benefit if it's potentially causing other issues. 
Or is this change to help people with older boxes, in which case why do certain individuals keep saying we need to move forward.

**Comment by AbuBaniaz** [comment] 2019-02-25 22:25
We have reverted the changes.

**Closed by AbuBaniaz** 2019-02-25 22:25 UTC

**Comment by RobvanderDoes** [comment] 2019-02-26 06:52
> > "The days of one skin fits all are long over, years ago.".
> 
> .. er no.. for the last 3 years I spent a lot of time making my skins work for as many OE-alliance builds as possible. Yes it is a lot more effort which is why most skinners don't. But it is still rewarding to do so, and then frustrating when 1 image decides to break things.

Indeed: when not using all options and innovations it's quite easy to make a 'one skin fits all'. But that easy way out is not what I meant.....

> I explained what my code was doing.
> For example. I might have 10 images in a folder.
> tile1.png
> tile2.png
> tile3.png
> 
> Then via a cron, I run a particular py file which......

That's a description, not code. And adding 'a particular py' to a skin is not done; it's changing E2. As I said before: you can't expect an image to be adapted for your skin; that would be the world upside down. And using 'a particular py' even means it's impossible to take a skin in consideration. That's why we have dedicated skins on our feeds for which we do take care.
